### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by IanRamosC** [mabrasil/slides-unidev-2015#1]
## Agenda
- Um pouco de história
  
  > Something here...
- Os problemas do presente
  
  > Something here...
- A programação funcional
  
  > Something here...
- Alguns casos
  - Empresas que usam Scala:
    - LinkedIn
    - Twitter
    - The Guardian
    - Sony
    - [Entre outras](http://www.scala-lang.org/old/node/1658)
  - Empresas que usam Clojure:
    - Akamai
    - Citi
    - backtype
    - factual
    - [Entre outras](http://clojure.org/Companies)
  - Empresas que usam Erlang:
    - Facebook
    - RabbitMQ
    - Whatsapp
    - Lindenbaum
    - [Entre outras](http://www.erlang.org/faq/introduction.html)
- O futuro
  
  > Something here...
- Por onde começar
  
  > Something here...

**Comment by IanRamosC** [comment]
@mabrasil Só pra trackear. :v

**Comment by ythecombinator** [comment]
Casos de uso, casos de uso everywhere :smile: 

Empresas que usam Erlang:
- Facebook, no backend de seu sistema de chat, lidando com 100 milhões de usuários ativos
- Delicious, que tem mais de 5 milhões de usuários e mais de 150 milhões de bookmarks;
- Amazon SimpleDB, o serviço de dados do poderoso Amazon EC2;
- GitHub, no seu sistema de backend, lidando com milhares de transações concorrentes;
- Motorola;
- CouchDB;
- RabbitMQ.
- [Entre outras](http://www.infoq.com/br/news/2010/02/erlang-proximo-grande-projeto)

Empresas que usam Haskell:
- AT&T, na divisão de Segurança de Rede para automatizar o processamento de queixas de abuso de internet;
- Facebook, que usa Haskell para desenvolvimento de algumas ferramentas internas, como, por exemplo, o lex-pass, uma ferramenta que era usada para manipulação de bases de código PHP;
- Google, que é usado em alguns projetos internos, relacionados principalmente a infra-estrutura de TI - como o projeto Ganeti, que é uma ferramenta para gerenciamento de clusters de servidores virtuais construídos em cima de Xen e KVM;
- Intel, em pesquisas envolvendo paralelismo multicore em escala - artigo disponível aqui;
- Microsoft, em seu sistema de serialização produção, Bond - que é amplamente utilizado na Microsoft em serviços de alta escala;
- The New York Times, onde foi usado no processamento de imagens de grande eventos, como a New York Fashion Week de 2013 - e foi escolhido, dentre outros motivos, pela facilidade de paralelização;
- NVIDIA, onde há uma grande quantidade de ferramentas internas que são escritas em Haskell
- [Entre outras](https://wiki.haskell.org/Haskell_in_industry)
